### ISSUE TITLE
能否做个golang binding

### ISSUE THREAD

**Issue by leitwolf** [lc-ui/lc-design#10]
能否导出个dll，然后做成golang binding，这样就可以用go来代替c了。

**Comment by leitwolf** [comment]
发错了，应该发到LCUI仓库下。。。

**Comment by lc-soft** [comment]
建议先查看 README.zh-cn.md 里的常见问题。

![image](https://user-images.githubusercontent.com/1730073/75784507-3fcefd80-5d9d-11ea-9b03-77a178ac55f4.png)
